export const NETWORK_LAN_DISCOVERY_PORT4 = 19132;
export const NETWORK_LAN_DISCOVERY_PORT6 = 19133;
export const NETWORK_ANY_ADDRESS4 = '0.0.0.0';
export const NETWORK_LOOPBACK_ADDRESS4 = '127.0.0.1';
export const NETWORK_ANY_ADDRESS6 = '::0';
export const NETWORK_LOOPBACK_ADDRESS6 = '::1';
