///////////////////////////////////////////////
// This file is generated do not edit this file
///////////////////////////////////////////////

import { PacketIds } from './enums';
import {
   AnimatePacket,
   BiomeDefinitionListPacket,
   DisconnectPacket,
   EmoteListPacket,
   LevelChunkPacket,
   LoginPacket,
   MovePlayerPacket,
   NetworkChunkPublisherUpdatePacket,
   NetworkSettingsPacket,
   PlayStatusPacket,
   PlayerAuthInputPacket,
   RequestChunkRadiusPacket,
   RequestNetworkSettingsPacket,
   ResourcePackClientResponsePacket,
   ResourcePackDataInfoPacket,
   ResourcePackStackPacket,
   ResourcePacksInfoPacket,
   ServerboundLoadingScreenPacket,
   SetLocalPlayerAsInitializedPacket,
   StartGamePacket,
   ToastRequestPacket,
} from './packets';

export const PROTOCOL = {
   [PacketIds.Animate]: AnimatePacket,
   [PacketIds.BiomeDefinitionList]: BiomeDefinitionListPacket,
   [PacketIds.Disconnect]: DisconnectPacket,
   [PacketIds.EmoteList]: EmoteListPacket,
   [PacketIds.LevelChunk]: LevelChunkPacket,
   [PacketIds.Login]: LoginPacket,
   [PacketIds.MovePlayer]: MovePlayerPacket,
   [PacketIds.NetworkChunkPublisherUpdate]: NetworkChunkPublisherUpdatePacket,
   [PacketIds.NetworkSettings]: NetworkSettingsPacket,
   [PacketIds.PlayStatus]: PlayStatusPacket,
   [PacketIds.PlayerAuthInput]: PlayerAuthInputPacket,
   [PacketIds.RequestChunkRadius]: RequestChunkRadiusPacket,
   [PacketIds.RequestNetworkSettings]: RequestNetworkSettingsPacket,
   [PacketIds.ResourcePackClientResponse]: ResourcePackClientResponsePacket,
   [PacketIds.ResourcePackDataInfo]: ResourcePackDataInfoPacket,
   [PacketIds.ResourcePackStack]: ResourcePackStackPacket,
   [PacketIds.ResourcePacksInfo]: ResourcePacksInfoPacket,
   [PacketIds.ServerboundLoadingScreen]: ServerboundLoadingScreenPacket,
   [PacketIds.SetLocalPlayerAsInitialized]: SetLocalPlayerAsInitializedPacket,
   [PacketIds.StartGame]: StartGamePacket,
   [PacketIds.ToastRequest]: ToastRequestPacket,
} as const;

export interface InternalPacketPipelineMethods<T, R = void> {
   [PacketIds.Animate]?(source: T, packet: AnimatePacket): R;
   [PacketIds.BiomeDefinitionList]?(source: T, packet: BiomeDefinitionListPacket): R;
   [PacketIds.Disconnect]?(source: T, packet: DisconnectPacket): R;
   [PacketIds.EmoteList]?(source: T, packet: EmoteListPacket): R;
   [PacketIds.LevelChunk]?(source: T, packet: LevelChunkPacket): R;
   [PacketIds.Login]?(source: T, packet: LoginPacket): R;
   [PacketIds.MovePlayer]?(source: T, packet: MovePlayerPacket): R;
   [PacketIds.NetworkChunkPublisherUpdate]?(source: T, packet: NetworkChunkPublisherUpdatePacket): R;
   [PacketIds.NetworkSettings]?(source: T, packet: NetworkSettingsPacket): R;
   [PacketIds.PlayStatus]?(source: T, packet: PlayStatusPacket): R;
   [PacketIds.PlayerAuthInput]?(source: T, packet: PlayerAuthInputPacket): R;
   [PacketIds.RequestChunkRadius]?(source: T, packet: RequestChunkRadiusPacket): R;
   [PacketIds.RequestNetworkSettings]?(source: T, packet: RequestNetworkSettingsPacket): R;
   [PacketIds.ResourcePackClientResponse]?(source: T, packet: ResourcePackClientResponsePacket): R;
   [PacketIds.ResourcePackDataInfo]?(source: T, packet: ResourcePackDataInfoPacket): R;
   [PacketIds.ResourcePackStack]?(source: T, packet: ResourcePackStackPacket): R;
   [PacketIds.ResourcePacksInfo]?(source: T, packet: ResourcePacksInfoPacket): R;
   [PacketIds.ServerboundLoadingScreen]?(source: T, packet: ServerboundLoadingScreenPacket): R;
   [PacketIds.SetLocalPlayerAsInitialized]?(source: T, packet: SetLocalPlayerAsInitializedPacket): R;
   [PacketIds.StartGame]?(source: T, packet: StartGamePacket): R;
   [PacketIds.ToastRequest]?(source: T, packet: ToastRequestPacket): R;
}
